In [0]:
# Read the Data Set
#Read the dataset
#Drop the columns which are unique for all users like IDs (2.5 points)
#Distinguish the feature and target set (2.5 points)

In [0]:
import tensorflow as tf
tf.enable_eager_execution()


## REQUIRED LIBRARIES
# For data wrangling 
import numpy as np
import pandas as pd



In [3]:
tf.__version__

'1.15.0-rc3'

In [0]:
df = pd.read_csv('Churn_Modelling.csv', delimiter=',')

In [5]:
df.shape

(10000, 14)

In [6]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
# Check columns list and missing values
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [0]:
# Drop the columns as mentioned which are unique
df1 = df.drop(["RowNumber", "CustomerId","Surname"], axis = 1)


In [9]:
df1.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [10]:
#To find the Unique Values
df1.nunique()

CreditScore         460
Geography             3
Gender                2
Age                  70
Tenure               11
Balance            6382
NumOfProducts         4
HasCrCard             2
IsActiveMember        2
EstimatedSalary    9999
Exited                2
dtype: int64

In [11]:
#Conversion of Categorical variables to numeric,as the model will consider only numeric values i.e  Geography and Gender is to be econverted
df2 = pd.get_dummies(df1, columns=["Geography","Gender"])
df2.head(10)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   
5          645   44       8  113755.78              2          1   
6          822   50       7       0.00              2          1   
7          376   29       4  115046.74              4          1   
8          501   44       4  142051.07              2          0   
9          684   27       2  134603.88              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1                 1   
1               1        112542.58       0                 0   
2               0        113931.57       1                 1   
3               0         93826.63       0                 1   
4               1         79084.10       0                 0   
5               0        149756.71       1                 0   
6               1         10062.80       0                 1   
7               0        119346.88       1                 0   
8               1         74940.50       0                 1   
9               1         71725.73       0                 1   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                  0                0              1            0  
1                  0                1              1            0  
2                  0                0              1            0  
3                  0                0              1            0  
4                  0                1              1            0  
5                  0                1              0            1  
6                  0                0              0            1  
7                  1                0              1            0  
8                  0                0              0            1  
9                  0                0              0            1

In [12]:
#as model will accept only Float so entire dataset is to be converted into float32
df3= df2.astype('float32')
df3.head()

CreditScore   Age  Tenure        Balance  NumOfProducts  HasCrCard  \
0        619.0  42.0     2.0       0.000000            1.0        1.0   
1        608.0  41.0     1.0   83807.859375            1.0        0.0   
2        502.0  42.0     8.0  159660.796875            3.0        1.0   
3        699.0  39.0     1.0       0.000000            2.0        0.0   
4        850.0  43.0     2.0  125510.820312            1.0        1.0   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0             1.0    101348.882812     1.0               1.0   
1             1.0    112542.578125     0.0               0.0   
2             0.0    113931.570312     1.0               1.0   
3             0.0     93826.632812     0.0               1.0   
4             1.0     79084.101562     0.0               0.0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                0.0              0.0            1.0          0.0  
1                0.0              1.0            1.0          0.0  
2                0.0              0.0            1.0          0.0  
3                0.0              0.0            1.0          0.0  
4                0.0              1.0            1.0          0.0

In [13]:
#Setting X & Y
X = df3.iloc[:,:13].values
print(X)
X.shape

[[619.  42.   2. ...   0.   0.   1.]
 [608.  41.   1. ...   0.   1.   1.]
 [502.  42.   8. ...   0.   0.   1.]
 ...
 [709.  36.   7. ...   0.   0.   1.]
 [772.  42.   3. ...   1.   0.   0.]
 [792.  28.   4. ...   0.   0.   1.]]


(10000, 13)

In [14]:
y = df3.iloc[:, 13].values
print(y)
y.shape


[0. 0. 0. ... 0. 1. 0.]


(10000,)

In [0]:
#Divide the data set into Train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
#conversion of X train & Y train to float
X_train = X_train.astype('float32')
y_train = y_train.astype('float32')

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

#Reshaping of Data
model.add(tf.keras.layers.Dense(1000, activation='relu', input_shape=(13,)))

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(500, activation='relu'))

model.add(tf.keras.layers.Dense(100, activation='sigmoid'))


In [0]:
#Create optimizer with non-default learning rate
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.05)


In [0]:
#Compile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [21]:
model.fit(X_train, y_train, 
          epochs=100,
          batch_size=10)

Train on 8000 samples
Epoch 1/100
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
8000/8000 [==============================] - 8s 1ms/sample - loss: 250.4169 - acc: 0.0103
Epoch 2/100
8000/8000 [==============================] - 5s 680us/sample - loss: 250.4093 - acc: 0.0093
Epoch 3/100
8000/8000 [==============================] - 5s 667us/sample - loss: 250.4079 - acc: 0.0082
Epoch 4/100
8000/8000 [==============================] - 5s 685us/sample - loss: 250.4072 - acc: 0.0070
Epoch 5/100
8000/8000 [==============================] - 6s 690us/sample - loss: 250.4068 - acc: 0.0088
Epoch 6/100
8000/8000 [==============================] - 5s 676us/sample - loss: 250.4066 - acc: 0.0120
Epoch 7/100
8000/8000 [==============================] - 6s 691us/sample - loss: 250.4064 - acc: 0.0137
Epoch 8/100
8000/8000 [==============================] - 5s 681us/sample - loss: 250.4063 - acc: 0.0149
Epoch 9/100
8000/8000 [==============================]

In [23]:
#The Accuracy of the predicted values

model.evaluate(X_test,y_test)

2000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[254.8961845703125, 0.0055]

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization (BatchNo multiple                  52        
_________________________________________________________________
dense (Dense)                multiple                  14000     
_________________________________________________________________
dense_1 (Dense)              multiple                  500500    
_________________________________________________________________
dense_2 (Dense)              multiple                  50100     
Total params: 564,652
Trainable params: 564,626
Non-trainable params: 26
_________________________________________________________________


In [0]:
#Note:the percentage of churn customers is about 20%.

In [25]:
#Model prediction
prediction = model.predict(X_test[0:1])

#Print prediction
print(prediction)

[[0.49589273 0.5040745  0.5005927  0.5077909  0.50776017 0.50152475
  0.49418592 0.5029827  0.51097316 0.5012106  0.50956076 0.5038545
  0.50271523 0.50301254 0.50534576 0.5062377  0.49836922 0.50088125
  0.5020856  0.5041942  0.5088757  0.50006884 0.49879152 0.5058291
  0.50465906 0.50150514 0.49863166 0.49750587 0.49593228 0.50072676
  0.50573725 0.5012883  0.5082331  0.49842593 0.5017279  0.5018077
  0.50226575 0.50217444 0.50280243 0.50413394 0.50055003 0.5025562
  0.49231428 0.49905854 0.49766654 0.5001809  0.50614333 0.50222224
  0.5031989  0.50022405 0.4954148  0.5079051  0.49532008 0.49990207
  0.5043508  0.49970964 0.5039594  0.50459045 0.507677   0.4995642
  0.5020537  0.4979257  0.5004015  0.502705   0.5026984  0.50111175
  0.5049265  0.50131154 0.49912784 0.4982302  0.50239134 0.49797404
  0.50492126 0.50640446 0.5040341  0.5095405  0.5094358  0.4985921
  0.49919587 0.5088455  0.50231004 0.50811297 0.50343066 0.50786626
  0.5052618  0.50136703 0.49867046 0.4986442  0.505127

In [41]:
from sklearn.linear_model import LogisticRegression

X_train = df3.drop(["Exited"], axis=1)
y_train = df3.Exited
X_test  = df3.drop(["Exited"], axis=1).copy()
y_test  = df3.Exited

# Logistic Regression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
Y_pred = logreg.predict(X_test)
#print(Y_pred)
acc_log = round(logreg.score(X_test, y_test), 3)
print("accuracy:", acc_log)



accuracy: 0.789


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [42]:
from sklearn.ensemble import GradientBoostingClassifier

X_train = df3.drop(["Exited"], axis=1)
y_train = df3.Exited
X_test  = df3.drop(["Exited"], axis=1).copy()
Y_test = df3.Exited

gbc = GradientBoostingClassifier(n_estimators = 20, learning_rate = 1.0, max_depth = 10, random_state = 0)
gbc.fit(X_train, y_train)
Y_pred = gbc.predict(X_test)
print("accuracy:", gbc.score(X_test, y_test))


accuracy: 1.0


In [43]:
# Gradient Boosting Regressor
from sklearn.ensemble import GradientBoostingRegressor

X_train = df3.drop(["Exited"], axis=1)
y_train = df3.Exited
X_test  = df3.drop(["Exited"], axis=1).copy()
Y_test = df3.Exited

gbc = GradientBoostingRegressor(n_estimators = 20, learning_rate = 1.0, max_depth = 10, random_state = 0, loss = "ls")
gbc.fit(X_train, y_train)
Y_pred = gbc.predict(X_test)
print("accuracy:", gbc.score(X_test, y_test))

accuracy: 0.9576056746389561


In [52]:
X_train = df3.drop(["Exited"], axis=1)
y_train = df3.Exited
X_test  = df3.drop(["Exited"], axis=1).copy()
y_test  = df3.Exited

y_pred = model.predict(X_test)
y_pred



array([[0.0000000e+00, 2.9802322e-08, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [0.0000000e+00, 5.3942204e-05, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00]], dtype=float32)

In [53]:
y_pred = (y_pred > 0.5)#if y_pred is larger than 0.5 it returns true(1) else false(2)
print(y_pred)


[[False False  True ... False  True  True]
 [False False  True ... False False  True]
 [False False  True ... False False False]
 ...
 [False False  True ... False  True  True]
 [False False  True ... False False  True]
 [ True False  True ... False  True False]]
